name: Build and Publish Docker Images

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          docker build -t dynamik-dev/laravel-docker:${VERSION} .
          docker push dynamik-dev/laravel-docker:${VERSION}